server:
  port: 8112
  servlet:
    context-path: /api

spring:
  ai:
    dashscope:
      api-key: ${spring.ai.dashscope.api-key}
      chat:
        options:
          model: qwen-plus
    mcp:
      client:
        stdio:
          servers-configuration: classpath:mcp-servers.json

  redisson:
    host: ${spring.redisson.host}
    port: ${spring.redisson.port}
    password: ${spring.redisson.password}
    database: ${spring.redisson.database}

  rabbitmq:
    host: ${spring.rabbitmq.host}
    port: ${spring.rabbitmq.port}
    username: ${spring.rabbitmq.username}
    password: ${spring.rabbitmq.password}
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual

  profiles:
    active: local
  application:
    name: fawn-health

  data:
    redis:
      database: ${spring.data.redis.database}
      host: ${spring.data.redis.host}
      port: ${spring.data.redis.port}
      password: ${spring.data.redis.password}
      timeout: 10000
    mongodb:
      uri: ${spring.data.mongodb.uri}
      username: ${spring.data.mongodb.username}
      password: ${spring.data.mongodb.password}

  datasource:
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: ${spring.datasource.mysql.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
    postgres:
      url: ${spring.datasource.postgres.url}
      username: ${spring.datasource.postgres.username}
      password: ${spring.datasource.postgres.password}
      driver-class-name: org.postgresql.Driver

  mail:
    host: smtp.163.com
    protocol: smtps
    port: 587
    username: ${spring.mail.username}
    password: ${spring.mail.password}
    nickname: 小鹿健康
    default-encoding: UTF-8
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

ali:
  oss:
    endpoint: ${ali.oss.endpoint}
    access-key-id: ${ali.oss.access-key-id}
    access-key-secret: ${ali.oss.access-key-secret}
    bucket-name: ${ali.oss.bucket-name}

sky:
  jwt:
    user-secret-key: ${sky.jwt.user-secret-key}
    user-ttl: 7200000
    user-token-name: token

load:
  documents:
    on:
      startup: true

zhipu:
  api-key: ${zhipu.api-key}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.ljh.fawnhealth.controller

knife4j:
  enable: true
  setting:
    language: zh_cn
